// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webhoctienganh.Data;

#nullable disable

namespace webhoctienganh.Migrations
{
    [DbContext(typeof(du_lieu))]
    [Migration("20260306094357_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("webhoctienganh.Models.bai_hoc", b =>
                {
                    b.Property<int>("ma_bai_hoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ma_khoa_hoc")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("TEXT");

                    b.Property<string>("nguoi_tao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("noi_dung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("tieu_de")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ma_bai_hoc");

                    b.HasIndex("ma_khoa_hoc");

                    b.HasIndex("nguoi_tao");

                    b.ToTable("bai_hoc");
                });

            modelBuilder.Entity("webhoctienganh.Models.bai_kiem_tra", b =>
                {
                    b.Property<int>("ma_bai_kiem_tra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ma_khoa_hoc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nguoi_tao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("thoi_luong_phut")
                        .HasColumnType("INTEGER");

                    b.Property<string>("tieu_de")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ma_bai_kiem_tra");

                    b.HasIndex("ma_khoa_hoc");

                    b.HasIndex("nguoi_tao");

                    b.ToTable("bai_kiem_tra");
                });

            modelBuilder.Entity("webhoctienganh.Models.cau_hoi", b =>
                {
                    b.Property<int>("ma_cau_hoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ma_bai_kiem_tra")
                        .HasColumnType("INTEGER");

                    b.Property<string>("noi_dung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ma_cau_hoi");

                    b.HasIndex("ma_bai_kiem_tra");

                    b.ToTable("cau_hoi");
                });

            modelBuilder.Entity("webhoctienganh.Models.dang_ky_model", b =>
                {
                    b.Property<int>("ma_dang_ky")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ma_hoc_vien")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ma_lop_hoc")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ngay_dang_ky")
                        .HasColumnType("TEXT");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ma_dang_ky");

                    b.HasIndex("ma_hoc_vien");

                    b.HasIndex("ma_lop_hoc");

                    b.ToTable("dang_ky");
                });

            modelBuilder.Entity("webhoctienganh.Models.danh_gia", b =>
                {
                    b.Property<int>("ma_danh_gia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ma_hoc_vien")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ma_khoa_hoc")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ngay_danh_gia")
                        .HasColumnType("TEXT");

                    b.Property<string>("noi_dung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("so_sao")
                        .HasColumnType("INTEGER");

                    b.HasKey("ma_danh_gia");

                    b.HasIndex("ma_hoc_vien");

                    b.HasIndex("ma_khoa_hoc");

                    b.ToTable("danh_gia");
                });

            modelBuilder.Entity("webhoctienganh.Models.dap_an", b =>
                {
                    b.Property<int>("ma_dap_an")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("la_dap_an_dung")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ma_cau_hoi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("noi_dung")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ma_dap_an");

                    b.HasIndex("ma_cau_hoi");

                    b.ToTable("dap_an");
                });

            modelBuilder.Entity("webhoctienganh.Models.hoa_don", b =>
                {
                    b.Property<int>("ma_hoa_don")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ma_dang_ky")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("so_tien")
                        .HasColumnType("TEXT");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ma_hoa_don");

                    b.HasIndex("ma_dang_ky")
                        .IsUnique();

                    b.ToTable("hoa_don");
                });

            modelBuilder.Entity("webhoctienganh.Models.ket_qua_kiem_tra", b =>
                {
                    b.Property<int>("ma_ket_qua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("diem_so")
                        .HasColumnType("TEXT");

                    b.Property<int>("ma_bai_kiem_tra")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ma_hoc_vien")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ngay_lam_bai")
                        .HasColumnType("TEXT");

                    b.HasKey("ma_ket_qua");

                    b.HasIndex("ma_bai_kiem_tra");

                    b.HasIndex("ma_hoc_vien");

                    b.ToTable("ket_qua_kiem_tra");
                });

            modelBuilder.Entity("webhoctienganh.Models.khoa_hoc", b =>
                {
                    b.Property<int>("ma_khoa_hoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("hoc_phi")
                        .HasColumnType("TEXT");

                    b.Property<string>("mo_ta")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nguoi_tao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ten_khoa_hoc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("thoi_luong_tuan")
                        .HasColumnType("INTEGER");

                    b.Property<string>("trinh_do")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ma_khoa_hoc");

                    b.HasIndex("nguoi_tao");

                    b.ToTable("khoa_hoc");
                });

            modelBuilder.Entity("webhoctienganh.Models.lich_hoc", b =>
                {
                    b.Property<int>("ma_lich_hoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("gio_bat_dau")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("gio_ket_thuc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ma_lop_hoc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("phong_hoc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("thu_trong_tuan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ma_lich_hoc");

                    b.HasIndex("ma_lop_hoc");

                    b.ToTable("lich_hoc");
                });

            modelBuilder.Entity("webhoctienganh.Models.lop_hoc", b =>
                {
                    b.Property<int>("ma_lop_hoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ma_giao_vien")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ma_khoa_hoc")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ngay_bat_dau")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ngay_ket_thuc")
                        .HasColumnType("TEXT");

                    b.Property<int>("so_luong_toi_da")
                        .HasColumnType("INTEGER");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ma_lop_hoc");

                    b.HasIndex("ma_giao_vien");

                    b.HasIndex("ma_khoa_hoc");

                    b.ToTable("lop_hoc");
                });

            modelBuilder.Entity("webhoctienganh.Models.nguoi_dung", b =>
                {
                    b.Property<string>("ma_nguoi_dung")
                        .HasColumnType("TEXT");

                    b.Property<string>("anh_dai_dien")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ho_ten")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("mat_khau_hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ngay_tao")
                        .HasColumnType("TEXT");

                    b.Property<string>("so_dien_thoai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ma_nguoi_dung");

                    b.HasIndex("email")
                        .IsUnique();

                    b.ToTable("nguoi_dung");
                });

            modelBuilder.Entity("webhoctienganh.Models.nguoi_dung_vai_tro", b =>
                {
                    b.Property<string>("ma_nguoi_dung")
                        .HasColumnType("TEXT");

                    b.Property<string>("ma_vai_tro")
                        .HasColumnType("TEXT");

                    b.HasKey("ma_nguoi_dung", "ma_vai_tro");

                    b.HasIndex("ma_vai_tro");

                    b.ToTable("nguoi_dung_vai_tro");
                });

            modelBuilder.Entity("webhoctienganh.Models.tai_lieu", b =>
                {
                    b.Property<int>("ma_tai_lieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("duong_dan_file")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("loai_tai_lieu")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ma_bai_hoc")
                        .HasColumnType("INTEGER");

                    b.HasKey("ma_tai_lieu");

                    b.HasIndex("ma_bai_hoc");

                    b.ToTable("tai_lieu");
                });

            modelBuilder.Entity("webhoctienganh.Models.thanh_toan", b =>
                {
                    b.Property<int>("ma_thanh_toan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ma_hoa_don")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ngay_thanh_toan")
                        .HasColumnType("TEXT");

                    b.Property<string>("phuong_thuc_thanh_toan")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("trang_thai")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ma_thanh_toan");

                    b.HasIndex("ma_hoa_don")
                        .IsUnique();

                    b.ToTable("thanh_toan");
                });

            modelBuilder.Entity("webhoctienganh.Models.vai_tro", b =>
                {
                    b.Property<string>("ma_vai_tro")
                        .HasColumnType("TEXT");

                    b.Property<string>("ten_vai_tro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ma_vai_tro");

                    b.ToTable("vai_tro");

                    b.HasData(
                        new
                        {
                            ma_vai_tro = "user",
                            ten_vai_tro = "Hoc vien"
                        },
                        new
                        {
                            ma_vai_tro = "teacher",
                            ten_vai_tro = "Giao vien"
                        },
                        new
                        {
                            ma_vai_tro = "admin",
                            ten_vai_tro = "Quan tri vien"
                        });
                });

            modelBuilder.Entity("webhoctienganh.Models.bai_hoc", b =>
                {
                    b.HasOne("webhoctienganh.Models.khoa_hoc", "khoa_hoc")
                        .WithMany("bai_hocs")
                        .HasForeignKey("ma_khoa_hoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webhoctienganh.Models.nguoi_dung", "nguoi_tao_nav")
                        .WithMany()
                        .HasForeignKey("nguoi_tao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("khoa_hoc");

                    b.Navigation("nguoi_tao_nav");
                });

            modelBuilder.Entity("webhoctienganh.Models.bai_kiem_tra", b =>
                {
                    b.HasOne("webhoctienganh.Models.khoa_hoc", "khoa_hoc")
                        .WithMany("bai_kiem_tras")
                        .HasForeignKey("ma_khoa_hoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webhoctienganh.Models.nguoi_dung", "nguoi_tao_nav")
                        .WithMany()
                        .HasForeignKey("nguoi_tao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("khoa_hoc");

                    b.Navigation("nguoi_tao_nav");
                });

            modelBuilder.Entity("webhoctienganh.Models.cau_hoi", b =>
                {
                    b.HasOne("webhoctienganh.Models.bai_kiem_tra", "bai_kiem_tra")
                        .WithMany("cau_hois")
                        .HasForeignKey("ma_bai_kiem_tra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bai_kiem_tra");
                });

            modelBuilder.Entity("webhoctienganh.Models.dang_ky_model", b =>
                {
                    b.HasOne("webhoctienganh.Models.nguoi_dung", "hoc_vien")
                        .WithMany("dang_kys")
                        .HasForeignKey("ma_hoc_vien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("webhoctienganh.Models.lop_hoc", "lop_hoc")
                        .WithMany("dang_kys")
                        .HasForeignKey("ma_lop_hoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("hoc_vien");

                    b.Navigation("lop_hoc");
                });

            modelBuilder.Entity("webhoctienganh.Models.danh_gia", b =>
                {
                    b.HasOne("webhoctienganh.Models.nguoi_dung", "hoc_vien")
                        .WithMany("danh_gias")
                        .HasForeignKey("ma_hoc_vien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("webhoctienganh.Models.khoa_hoc", "khoa_hoc")
                        .WithMany("danh_gias")
                        .HasForeignKey("ma_khoa_hoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("hoc_vien");

                    b.Navigation("khoa_hoc");
                });

            modelBuilder.Entity("webhoctienganh.Models.dap_an", b =>
                {
                    b.HasOne("webhoctienganh.Models.cau_hoi", "cau_hoi")
                        .WithMany("dap_ans")
                        .HasForeignKey("ma_cau_hoi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cau_hoi");
                });

            modelBuilder.Entity("webhoctienganh.Models.hoa_don", b =>
                {
                    b.HasOne("webhoctienganh.Models.dang_ky_model", "dang_ky")
                        .WithOne("hoa_don")
                        .HasForeignKey("webhoctienganh.Models.hoa_don", "ma_dang_ky")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("dang_ky");
                });

            modelBuilder.Entity("webhoctienganh.Models.ket_qua_kiem_tra", b =>
                {
                    b.HasOne("webhoctienganh.Models.bai_kiem_tra", "bai_kiem_tra")
                        .WithMany("ket_quas")
                        .HasForeignKey("ma_bai_kiem_tra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webhoctienganh.Models.nguoi_dung", "hoc_vien")
                        .WithMany("ket_quas")
                        .HasForeignKey("ma_hoc_vien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("bai_kiem_tra");

                    b.Navigation("hoc_vien");
                });

            modelBuilder.Entity("webhoctienganh.Models.khoa_hoc", b =>
                {
                    b.HasOne("webhoctienganh.Models.nguoi_dung", "nguoi_tao_nav")
                        .WithMany()
                        .HasForeignKey("nguoi_tao")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("nguoi_tao_nav");
                });

            modelBuilder.Entity("webhoctienganh.Models.lich_hoc", b =>
                {
                    b.HasOne("webhoctienganh.Models.lop_hoc", "lop_hoc")
                        .WithMany("lich_hocs")
                        .HasForeignKey("ma_lop_hoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("lop_hoc");
                });

            modelBuilder.Entity("webhoctienganh.Models.lop_hoc", b =>
                {
                    b.HasOne("webhoctienganh.Models.nguoi_dung", "giao_vien")
                        .WithMany("lop_giang_days")
                        .HasForeignKey("ma_giao_vien")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("webhoctienganh.Models.khoa_hoc", "khoa_hoc")
                        .WithMany("lop_hocs")
                        .HasForeignKey("ma_khoa_hoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("giao_vien");

                    b.Navigation("khoa_hoc");
                });

            modelBuilder.Entity("webhoctienganh.Models.nguoi_dung_vai_tro", b =>
                {
                    b.HasOne("webhoctienganh.Models.nguoi_dung", "nguoi_dung")
                        .WithMany("vai_tros")
                        .HasForeignKey("ma_nguoi_dung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webhoctienganh.Models.vai_tro", "vai_tro")
                        .WithMany("nguoi_dungs")
                        .HasForeignKey("ma_vai_tro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("nguoi_dung");

                    b.Navigation("vai_tro");
                });

            modelBuilder.Entity("webhoctienganh.Models.tai_lieu", b =>
                {
                    b.HasOne("webhoctienganh.Models.bai_hoc", "bai_hoc")
                        .WithMany("tai_lieus")
                        .HasForeignKey("ma_bai_hoc")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bai_hoc");
                });

            modelBuilder.Entity("webhoctienganh.Models.thanh_toan", b =>
                {
                    b.HasOne("webhoctienganh.Models.hoa_don", "hoa_don")
                        .WithOne("thanh_toan")
                        .HasForeignKey("webhoctienganh.Models.thanh_toan", "ma_hoa_don")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("hoa_don");
                });

            modelBuilder.Entity("webhoctienganh.Models.bai_hoc", b =>
                {
                    b.Navigation("tai_lieus");
                });

            modelBuilder.Entity("webhoctienganh.Models.bai_kiem_tra", b =>
                {
                    b.Navigation("cau_hois");

                    b.Navigation("ket_quas");
                });

            modelBuilder.Entity("webhoctienganh.Models.cau_hoi", b =>
                {
                    b.Navigation("dap_ans");
                });

            modelBuilder.Entity("webhoctienganh.Models.dang_ky_model", b =>
                {
                    b.Navigation("hoa_don");
                });

            modelBuilder.Entity("webhoctienganh.Models.hoa_don", b =>
                {
                    b.Navigation("thanh_toan");
                });

            modelBuilder.Entity("webhoctienganh.Models.khoa_hoc", b =>
                {
                    b.Navigation("bai_hocs");

                    b.Navigation("bai_kiem_tras");

                    b.Navigation("danh_gias");

                    b.Navigation("lop_hocs");
                });

            modelBuilder.Entity("webhoctienganh.Models.lop_hoc", b =>
                {
                    b.Navigation("dang_kys");

                    b.Navigation("lich_hocs");
                });

            modelBuilder.Entity("webhoctienganh.Models.nguoi_dung", b =>
                {
                    b.Navigation("dang_kys");

                    b.Navigation("danh_gias");

                    b.Navigation("ket_quas");

                    b.Navigation("lop_giang_days");

                    b.Navigation("vai_tros");
                });

            modelBuilder.Entity("webhoctienganh.Models.vai_tro", b =>
                {
                    b.Navigation("nguoi_dungs");
                });
#pragma warning restore 612, 618
        }
    }
}
